// <auto-generated />
using System;
using ControlRH.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlRH.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251001011245_Implementacao_Inicial")]
    partial class Implementacao_Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cargo", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.CarteiraCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CarteiraCliente", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CarteiraClienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Pis")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("CarteiraClienteId");

                    b.ToTable("Colaborador", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.ColaboradorJornada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("JornadaTrabalhoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("JornadaTrabalhoId");

                    b.ToTable("ColaboradorJornada", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("CarteiraClienteId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ColaboradorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CarteiraClienteId");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Grupo", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.GrupoPermissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("GrupoPermissao", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.JornadaTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("JornadaTrabalho", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.JornadaTrabalhoHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("DuracaoIntervalo")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraSaida")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("JornadaTrabalhoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("JornadaTrabalhoId");

                    b.ToTable("JornadaTrabalhoHorario", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Permissao", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("DeveAlterarSenha")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.UsuarioGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioGrupo", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Colaborador.Models.AjusteMarcacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CpfResponsavelAjuste")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeResponsavelAjuste")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("PontoEletronicoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PontoEletronicoId");

                    b.ToTable("AjusteMarcacao", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Colaborador.Models.PontoEletronico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DataAlteracao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnderecoIp")
                        .HasColumnType("longtext");

                    b.Property<string>("HashUnico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hostname")
                        .HasColumnType("longtext");

                    b.Property<string>("Marcacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pis")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.ToTable("PontoEletronico", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Colaborador", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.Cargo", "Cargo")
                        .WithMany("Colaboradores")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlRH.Areas.Admin.Models.CarteiraCliente", "CarteiraCliente")
                        .WithMany("Colaboradores")
                        .HasForeignKey("CarteiraClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("CarteiraCliente");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.ColaboradorJornada", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.Colaborador", "Colaborador")
                        .WithMany("ColaboradoresJornadas")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlRH.Areas.Admin.Models.JornadaTrabalho", "JornadaTrabalho")
                        .WithMany("ColaboradoresJornadas")
                        .HasForeignKey("JornadaTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("JornadaTrabalho");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Documento", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.CarteiraCliente", "CarteiraCliente")
                        .WithMany("Documentos")
                        .HasForeignKey("CarteiraClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ControlRH.Areas.Admin.Models.Colaborador", "Colaborador")
                        .WithMany("Documentos")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CarteiraCliente");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.GrupoPermissao", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.Grupo", "Grupo")
                        .WithMany("GruposPermissoes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlRH.Areas.Admin.Models.Permissao", "Permissao")
                        .WithMany("GruposPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.JornadaTrabalhoHorario", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.JornadaTrabalho", "JornadaTrabalho")
                        .WithMany("JornadasTrabalhosHorarios")
                        .HasForeignKey("JornadaTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JornadaTrabalho");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Usuario", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.Colaborador", "Colaborador")
                        .WithOne()
                        .HasForeignKey("ControlRH.Areas.Admin.Models.Usuario", "ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.UsuarioGrupo", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.Grupo", "Grupo")
                        .WithMany("UsuariosGrupos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlRH.Areas.Admin.Models.Usuario", "Usuario")
                        .WithMany("UsuariosGrupos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlRH.Areas.Colaborador.Models.AjusteMarcacao", b =>
                {
                    b.HasOne("ControlRH.Areas.Colaborador.Models.PontoEletronico", "PontoEletronico")
                        .WithMany("AjustesMarcacoes")
                        .HasForeignKey("PontoEletronicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PontoEletronico");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Cargo", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.CarteiraCliente", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Colaborador", b =>
                {
                    b.Navigation("ColaboradoresJornadas");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Grupo", b =>
                {
                    b.Navigation("GruposPermissoes");

                    b.Navigation("UsuariosGrupos");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.JornadaTrabalho", b =>
                {
                    b.Navigation("ColaboradoresJornadas");

                    b.Navigation("JornadasTrabalhosHorarios");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Permissao", b =>
                {
                    b.Navigation("GruposPermissoes");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Usuario", b =>
                {
                    b.Navigation("UsuariosGrupos");
                });

            modelBuilder.Entity("ControlRH.Areas.Colaborador.Models.PontoEletronico", b =>
                {
                    b.Navigation("AjustesMarcacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
