// <auto-generated />
using System;
using ControlRH.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlRH.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.CarteiraCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CarteiraCliente", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CarteiraClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pis")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("CarteiraClienteId");

                    b.ToTable("Colaborador", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.ColaboradorJornada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JornadaTrabalhoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("JornadaTrabalhoId");

                    b.ToTable("ColaboradorJornada", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grupo", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.GrupoPermissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("GrupoPermissao", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.JornadaTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("JornadaTrabalho", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.JornadaTrabalhoHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("DuracaoIntervalo")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraSaida")
                        .HasColumnType("time");

                    b.Property<Guid>("JornadaTrabalhoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JornadaTrabalhoId");

                    b.ToTable("JornadaTrabalhoHorario", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Permissao", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.PontoEletronico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("PontoEletronico", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.PontoMarcacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("DispositivoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("time");

                    b.Property<string>("IPDispositivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigemMarcacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PontoEletronicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PontoEletronicoId");

                    b.ToTable("PontoMarcacao", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.PontoMarcacaoAjuste", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAjuste")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MarcacaoPontoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("NovoHorario")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("MarcacaoPontoId");

                    b.ToTable("PontoMarcacaoAjuste", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeveAlterarSenha")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.UsuarioGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioGrupo", (string)null);
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Colaborador", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.CarteiraCliente", "CarteiraCliente")
                        .WithMany("Colaboradores")
                        .HasForeignKey("CarteiraClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarteiraCliente");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.ColaboradorJornada", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.Colaborador", "Colaborador")
                        .WithMany("ColaboradoresJornadas")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlRH.Areas.Admin.Models.JornadaTrabalho", "JornadaTrabalho")
                        .WithMany("ColaboradoresJornadas")
                        .HasForeignKey("JornadaTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("JornadaTrabalho");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.GrupoPermissao", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.Grupo", "Grupo")
                        .WithMany("GruposPermissoes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlRH.Areas.Admin.Models.Permissao", "Permissao")
                        .WithMany("GruposPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.JornadaTrabalhoHorario", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.JornadaTrabalho", "JornadaTrabalho")
                        .WithMany("JornadasTrabalhosHorarios")
                        .HasForeignKey("JornadaTrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JornadaTrabalho");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.PontoEletronico", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.PontoMarcacao", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.PontoEletronico", null)
                        .WithMany("Marcacaos")
                        .HasForeignKey("PontoEletronicoId");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.PontoMarcacaoAjuste", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.PontoMarcacao", "MarcacaoPonto")
                        .WithMany()
                        .HasForeignKey("MarcacaoPontoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarcacaoPonto");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Usuario", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.Colaborador", "Colaborador")
                        .WithOne()
                        .HasForeignKey("ControlRH.Areas.Admin.Models.Usuario", "ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.UsuarioGrupo", b =>
                {
                    b.HasOne("ControlRH.Areas.Admin.Models.Grupo", "Grupo")
                        .WithMany("UsuariosGrupos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlRH.Areas.Admin.Models.Usuario", "Usuario")
                        .WithMany("UsuariosGrupos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.CarteiraCliente", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Colaborador", b =>
                {
                    b.Navigation("ColaboradoresJornadas");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Grupo", b =>
                {
                    b.Navigation("GruposPermissoes");

                    b.Navigation("UsuariosGrupos");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.JornadaTrabalho", b =>
                {
                    b.Navigation("ColaboradoresJornadas");

                    b.Navigation("JornadasTrabalhosHorarios");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Permissao", b =>
                {
                    b.Navigation("GruposPermissoes");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.PontoEletronico", b =>
                {
                    b.Navigation("Marcacaos");
                });

            modelBuilder.Entity("ControlRH.Areas.Admin.Models.Usuario", b =>
                {
                    b.Navigation("UsuariosGrupos");
                });
#pragma warning restore 612, 618
        }
    }
}
